### ISSUE TITLE
Python Help dentro do Docker

### ISSUE THREAD

**Issue by nerijunior** [CodeForCuritiba/c4c-gestao-br-scrapers#3]
Criei um container para o `gestao-br` porém estou recebendo esse erro e preciso da ajuda do @turicas ninja python da area:

```
root@c21f815af6cd:/home/gestao-br# source .env/bin/activate
(.env) root@c21f815af6cd:/home/gestao-br# python cli.py 2017 "FUNDO MUNICIPAL DE SAÚDE"
Downloading data...Traceback (most recent call last):
  File "/home/gestao-br/.env/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/local/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cli.py", line 78, in <module>
    main()
  File "cli.py", line 48, in main
    'MUNICIPIO DE MARMELEIRO', args.ano, args.unidade_gestora)
  File "/home/gestao-br/marmeleiro/crawler.py", line 58, in busca_licitacoes
    browser = MyBrowser()
  File "/home/gestao-br/.env/lib/python3.5/site-packages/splinter/driver/webdriver/firefox.py", line 48, in __init__
    timeout=timeout)
  File "/home/gestao-br/.env/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/home/gestao-br/.env/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.
```

## Para reproduzir

Para reproduzir o erro é necessário seguir o build e o run do Docker no [meu fork](https://github.com/nerijunior/gestao-br-scrapers/tree/feature/docker#docker) e rodar:

```
docker exec -it gestao-br bash
```

Após entrar no bash do container, rodar:

```
source .env/bin/activate
python cli.py 2017 "FUNDO MUNICIPAL DE SAÚDE"
```

**Comment by turicas** [comment]
@nerijunior, no README eu comento que você precisa do [driver do Firefox para o Selenium](https://github.com/mozilla/geckodriver/releases) - baixe-o e coloque em algum diretório que está no `PATH` do seu container (`/usr/bin`, por exemplo).

**Comment by nerijunior** [comment]
@turicas Agora fiquem em dúvida, instalei o driver, porém ainda tem uma exception:

```
Downloading data...Traceback (most recent call last):
  File "cli.py", line 78, in <module>
    main()
  File "cli.py", line 48, in main
    'MUNICIPIO DE MARMELEIRO', args.ano, args.unidade_gestora)
  File "/home/gestao-br/marmeleiro/crawler.py", line 58, in busca_licitacoes
    browser = MyBrowser()
  File "/home/gestao-br/.env/lib/python3.5/site-packages/splinter/driver/webdriver/firefox.py", line 48, in __init__
    timeout=timeout)
  File "/home/gestao-br/.env/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py", line 154, in __init__
    keep_alive=True)
  File "/home/gestao-br/.env/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/home/gestao-br/.env/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/gestao-br/.env/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "/home/gestao-br/.env/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line
```

Achei [uma solução](http://stackoverflow.com/questions/40208051/selenium-using-python-geckodriver-executable-needs-to-be-in-path) porém colocar o caminho hardcoded não é a melhor maneira, pensei em colocar uma variável no ENV, mas mesmo assim não é o melhor.

**Comment by turicas** [comment]
@nerijunior, além do driver você precisa do navegador instalado (nesse caso, o Firefox). Você precisará de um ambiente completo para rodar o Selenium (ambiente gráfico, navegador e driver).

**Comment by nerijunior** [comment]
@turicas Certo, como poderemos simular isso em um server, se um dia precisarmos rodar ele para pegar umas 20 ou 30 cidades, será complicado com um ambiente gráfico de um desktop.​

**Comment by turicas** [comment]
@nerijunior Não será complicado: é só instalar as dependências no servidor. Você pode, inclusive, usar o docker no servidor. 
Vamos resolver um problema de cada vez. Nem temos ainda muito código para preocupar agora em rodar em um servidor. :-) 
O passo atual é que todos que queiram colaborar consigam configurar o ambiente local para rodar o código. 
Quando tiver resolvido seu problema, por favor feche a issue.
